### ISSUE TITLE
`SHORT` on a variable will limit the string size to ~8 characters

### ISSUE THREAD

**Issue by FrankHeijden** [rlespinasse/github-slug-action#153]
As per the README.md:
### Others Slug-ish variables are available

- `SLUG_URL` on a variable to have a `slug` variable compliant to be used in a URL
  - Like `SLUG` but `.`, and `_` are also replaced by `-`
- `SHORT` on a variable will limit the string size to ~8 characters
  - Useful for _sha_ value

We just spent a bit debugging why our short hash suddenly increased from 7->8. Could you maybe clarify the design choice here?

It would probably be a good idea to have this be a fixed default length, either 7 or 8, with the option to have this configurable by env variable to the action.

**Comment by FrankHeijden** [comment]
Ok interesting, seems to be because it will prevent collisions on the hashes, as it's using `git rev-parse --short` behind the scenes. Interestingly enough, there's no collision for any commit in the repo.

**Comment by rlespinasse** [comment]
The [configuration point for this case](https://github.com/rlespinasse/github-slug-action?tab=readme-ov-file#with-another-length-for-short-values) is available.

```yaml
steps:
  - name: Inject enhanced GitHub environment variables
    uses: rlespinasse/github-slug-action@v5
    with:
      short-length: 7 # Keep the small repository behavior instead of the 'auto' sizing depending on the repository size.
```

The explanation for the behavior has been available in the [migration guide](https://github.com/rlespinasse/github-slug-action?tab=readme-ov-file#v3-to-v4) `v3 -> v4`

We could rework the documentation to make the `behavior` part to be more visible.
