### ISSUE TITLE
Don't dump env to the console for every slug

### ISSUE THREAD

**Issue by asarkar** [rlespinasse/github-slug-action#161]
**Describe the bug**
For every slug value, `rlespinasse/slugify-value` is run, which dumps the entire env to the console. Not only this clutters the console, it is also a major security risk as there may be sensitive information stored in environment variables.

**To Reproduce**
N/A

**Expected behavior**
Don't dump env to the console unless asked for. It seems this behavior can be controlled by `publish-env`, but this parameter is not available to the slug action.

**Screenshots**
```
Run rlespinasse/slugify-value@v1.4.0
  with:
    key: GITHUB_REPOSITORY_NAME_PART
    value: grpc-test
    slug-maxlength: 63
    publish-env: true
  env:
    GITHUB_REPOSITORY: asarkar/grpc-test
    ...dozens more
```
