### ISSUE TITLE
Use ref as input?

### ISSUE THREAD

**Issue by m0ppers** [rlespinasse/github-slug-action#18]
**Is your feature request related to a problem? Please describe.**

I have a CI pipeline in some web project that automatically updates test installations so that whenever somebody pushes some branches etc. there is a corresponding installation being setup where you can see the result. I am using this plugin to build docker images (or better put their tags) and publish them onto my testservers.

Now I have the problem that this creates many many test installations (which is expected ;) ). As PRs and branches are merged and closed the installations should go away as well. You can do that on github using

```
on: [delete]
```

in your workflow file. The problem is that this workflow is always being triggered on the default branch. This is obviously not really helpfult ;) The corresponding deleted branch/pr is available using `${{ github.event.ref }}`

**Describe the solution you'd like**

I want to reuse the exact same logic that I am using to deploy in this case. If I could optionally specify some tag input everything would be fine. Namely I want this plugin to support something like this:

```
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x
        with:
          # github.ref is always the default branch for deletion...need to extract branch from delete event!
          ref: ${{ github.event.ref }}
```

**Describe alternatives you've considered**

**Additional context**
