### ISSUE TITLE
Case-sensitive GITHUB_HEAD_REF_SLUG

### ISSUE THREAD

**Issue by cpeck-bi** [rlespinasse/github-slug-action#60]
**Is your feature request related to a problem? Please describe.**
I am using the GITHUB_HEAD_REF_SLUG to pass a branch name into an action. That variable is always lowercase, but my action needs the case-sensitive version of the slug.

**Describe the solution you'd like**
Branches are passed in with capital letters respected. Either in this variable or a new, case-sensitive one.

**Comment by rlespinasse** [comment]
@cpeck-bi I add a `_CS` suffix available on `_SLUG` or `_SLUG_URL` variables.

Waiting to be review and merged, you can test this PR using `rlespinasse/github-slug-action@sensitive`
```
name: Test it
on: push
jobs:
  test-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rlespinasse/github-slug-action@sensitive
      - name: Case-sensitive GITHUB_HEAD_REF_SLUG
        run: echo "head ref (case-sensitive): ${{ env.GITHUB_HEAD_REF_SLUG_CS }}"
```
