### ISSUE TITLE
Determine variable(s) from input

### ISSUE THREAD

**Issue by fmeriaux** [rlespinasse/github-slug-action#68]
**Is your feature request related to a problem? Please describe.**

Need: determine the slug version of an input variable.
Depending on the workflow, `github.ref` is not necessarily the desired value (especially for manual deployment workflow).

**Describe the solution you'd like**

A solution could be to allow to override `github.ref` with `ref` parameter (the default value remains what it is, so it is backward compatible).

```yaml
- name: Inject slug/short variables
  uses: rlespinasse/github-slug-action@v3.x
  with:
    ref: ${{ my-ref }}
```

**Describe alternatives you've considered**

Another solution could be to access the action's function via a script.

```yaml
- name: Inject slug/short variables
  uses: rlespinasse/github-slug-action@v3.x
  with:
    script: exportSlugRefCS("${{ my-ref }}", "MY_GITHUB_REF_SLUG_CS")
```

**Additional context**
n/a

**Comment by Johnnyb531** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> 
> 
> Need: determine the slug version of an input variable.
> 
> Depending on the workflow, `github.ref` is not necessarily the desired value (especially for manual deployment workflow).
> 
> 
> 
> **Describe the solution you'd like**
> 
> 
> 
> A solution could be to allow to override `github.ref` with `ref` parameter (the default value remains what it is, so it is backward compatible).
> 
> 
> 
> ```yaml
> 
> - name: Inject slug/short variables
> 
>   uses: rlespinasse/github-slug-action@v3.x
> 
>   with:
> 
>     ref: ${{ my-ref }}
> 
> ```
> 
> 
> 
> **Describe alternatives you've considered**
> 
> 
> 
> Another solution could be to access the action's function via a script.
> 
> 
> 
> ```yaml
> 
> - name: Inject slug/short variables
> 
>   uses: rlespinasse/github-slug-action@v3.x
> 
>   with:
> 
>     script: exportSlugRefCS("${{ my-ref }}", "MY_GITHUB_REF_SLUG_CS")
> 
> ```
> 
> 
> 
> **Additional context**
> 
> n/a
> 
>

**Comment by Johnnyb531** [comment]
Yes this is a Bitcoin.com wallet that funds disappeared

**Comment by rlespinasse** [comment]
This enhancement have been externalized in a new repository: [rlespinasse/slugify-value](https://github.com/rlespinasse/slugify-value)

For your example, the step will be

```yaml
- uses: rlespinasse/slugify-value@v1.x
  with:
    key: MY_GITHUB_REF
    value: ${{ my-ref }}
```
