### ISSUE TITLE
Feature wish: option to set a different slug length than 63

### ISSUE THREAD

**Issue by nkuehn** [rlespinasse/github-slug-action#87]
(updated to account for being able to use the prefix parameter)

**Is your feature request related to a problem? Please describe.**
I need a slug that, including our prefix, fits into less than 63 characters because I have a different length limit than 63. 

**Describe the solution you'd like**
an optional `with` parameter to set a different limit (or no limit if someone has that use case because technically branch names could collide). 

**Describe alternatives you've considered**
Custom scripting, e.g. an action step that runs a script that takes the env var and provides an output.  That's pretty near to building an own custom github action like this)

**Additional context**
Thank you very much for your work, this is a nice and useful action.

**Comment by rlespinasse** [comment]
Following rlespinasse/slugify-value#6, support the slug length configuration

```yaml
- uses: rlespinasse/github-slug-action@v4
   with:
     slug-maxlength: 63
     # or
     slug-maxlength: nolimit
```
